---
- name: Install Docker/HA
  hosts: ubuntu
  tasks:
    - name: Install Docker
      block:
        - name: Add repo universe (for all distrib)
          ansible.builtin.apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
        - name: Install additional package
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400
        - name: Add key Docker
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        - name: Install stable repo Docker
          ansible.builtin.apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker
        - name: Install Docker-ce & additional
          ansible.builtin.apt:
            name: 
              - docker-ce
              - docker-ce-cli
              - python3-docker
            update-cache: true
        - name: Check install & reboot Docker
          service:
            name: docker
            state: restarted
            enabled: true
      become: true
    - name: Install Docker-composer
      block:
        - name: Get last version docker-composer
          ansible.builtin.uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: Install docker-composer
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true
    - name: Configuration Docker
      block:
        - name: Finish install Docker
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true
        - name: Reboot server
          ansible.builtin.reboot:
      become: true
    - name: Run HomeAssistant container
      docker_container:
        name: HomeAssistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumes:
          - /home/homeassistant:/config
          - /etc/localtime:/etc/localtime:ro
        network_mode: host
